from django.db import models

class User(models.Model):
    # autogenerated id
    firebase_uid = models.CharField(max_length=255, blank=True, null=True)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=129)
    email = models.CharField(max_length=320)
    biography = models.TextField(null=True, blank=True)
    profile_picture = models.BinaryField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_online = models.DateTimeField(null=True, blank=True)

