# Generated by Django 4.2.6 on 2023-11-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_validated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
